### ISSUE TITLE
Idea: cache some of the requests somehow?

### ISSUE THREAD

**Issue by ionelmc** [AndiDittrich/GitHub-Buttons#1]
Turns out github has a limit of 60 requests per hour per IP. This can be easily hit by refreshing page with dozen buttons couple times :unamused: 

Maybe there's some way to cache these requests (like in some local storage)

**Comment by AndiDittrich** [comment]
Dear ionelmc,

it's a great idea to implement client-side caching with LocalStorage - i will implement it as soon as possible. Btw. the PHP version is already using server-side caching - for large sites i recommend to use this version.

best regards Andi

**Comment by AndiDittrich** [comment]
I've added LocalStorage caching feature to the jQuery as well as MooTools version and some enhancement to the php based caching: http://github-buttons.andidittrich.de/

This features are now available within v2.4.0

**Comment by ionelmc** [comment]
Awesome! :tada:
